server:
  port: 8086   # puerto HTTP del dispatch-consumer

spring:
  application:
    name: dispatch-consumer
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/cardsdb}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    root: INFO
    reactor.kafka: WARN
    com.bank.dispatch_consumer: INFO
  appender:
    logstash:
      # 👇 Si no hay variable ELASTIC_HOST definida, usará elasticsearch:5000 por defecto
      destination: ${ELASTIC_HOST:elasticsearch:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# 🔹 OpenTelemetry exporter (igual que en card-ops-producer)
otel:
  exporter:
    otlp:
      endpoint: http://otel-collector:4317
  resource:
    attributes:
      service.name: ${spring.application.name}
      service.version: 1.0.0   # ✅ agrega versión del servicio
  traces:                     # ✅ asegura muestreo de spans
    sampler:
      probability: 1.0

app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    group-id: dispatch-consumer
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
  topics:
    main: bank.card.replacements.v1
    dlt: bank.card.replacements.v1.DLT
