receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlphttp:
    endpoint: "http://apm-server:8200"   # ✅ exporta trazas a Elastic APM

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]     # ✅ trazas van al APM Server
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]   # ✅ métricas a Prometheus
